// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrAVsUoVhVTVC_gEBZDJ7GMPIBhZbi4M',
    appId: '1:466473133509:web:c5898d3729d18411a3d7ac',
    messagingSenderId: '466473133509',
    projectId: 'kitsmart-d776f',
    authDomain: 'kitsmart-d776f.firebaseapp.com',
    storageBucket: 'kitsmart-d776f.appspot.com',
    measurementId: 'G-CEM37D1Q15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoBfqjYvpTF0rlYR36Y1cpi1tf1t4Gh_Y',
    appId: '1:466473133509:android:c2346d1a34677f7ba3d7ac',
    messagingSenderId: '466473133509',
    projectId: 'kitsmart-d776f',
    storageBucket: 'kitsmart-d776f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnOMpJTaU8zboUZH5O5VRPaePvboU3v9I',
    appId: '1:466473133509:ios:17ff2f6d7ebac7dfa3d7ac',
    messagingSenderId: '466473133509',
    projectId: 'kitsmart-d776f',
    storageBucket: 'kitsmart-d776f.appspot.com',
    iosBundleId: 'com.example.kitsmart',
  );
}
