// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfAD2yxMT4LvX110dreQ1YdIb3gGQSV-k',
    appId: '1:786537118015:web:c7a479c819e9c2a20abb8a',
    messagingSenderId: '786537118015',
    projectId: 'kitsmart-fc6ad',
    authDomain: 'kitsmart-fc6ad.firebaseapp.com',
    storageBucket: 'kitsmart-fc6ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLR_cXr19_64OSK4DdK3oWj0FkEN37jeo',
    appId: '1:786537118015:android:484d2c35724b0d340abb8a',
    messagingSenderId: '786537118015',
    projectId: 'kitsmart-fc6ad',
    storageBucket: 'kitsmart-fc6ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSXP0sSpJlDVy35KAtlg959PvrDdLMoPo',
    appId: '1:786537118015:ios:2c32c736f3b9dc8a0abb8a',
    messagingSenderId: '786537118015',
    projectId: 'kitsmart-fc6ad',
    storageBucket: 'kitsmart-fc6ad.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
